# Site Info
title:              "Arno Polegato"
description:        "Arno Polegato - CV and Blog"
google_verify:      sLMRKNYbC4Ztmh9eix8n0Omx24eY3oyF8sCfdUjZE8M # Put your Google Verification here
google_analytics:   UA-83439726-1 # Put your Google Analytics code

# Author Info
author_name:        "Arno Polegato"
author_email:       arno.polegato@gmail.com
author_gravatar:    /arno-profile-close.png # Gravatar md5 hash
twitter_username:   NosyOwl

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /blog/:categories/:year/:month/:day/:title.html # Post permalink
timezone:           Europe/Amsterdam # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap
  - jemoji

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
      category:     "opinion"
      author:       "Arno Polegato"

